name: testing python code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check and Add testing.py
        run: |
          if [ ! -f "testing.py" ]; then
            echo "testing.py not found. Creating and adding it..."
            cat <<EOT > testing.py
          import os
          import sys
          sys.path.insert(0, os.path.abspath('.'))
          
          from main import Sum, Sub, Mul, Div
          
          def test_Sum():
              assert Sum(1, 2) == 3
              assert Sum(2, 2) == 4
              assert Sum(3, 3) == 6
          
          def test_Sub():
              assert Sub(1, 2) == -1
              assert Sub(2, 2) == 0
              assert Sub(3, 3) == 0
          
          def test_Mul():
              assert Mul(1, 2) == 2
              assert Mul(2, 2) == 4
              assert Mul(3, 3) == 9
          
          def test_Div():
              assert Div(1, 2) == 0.5
              assert Div(2, 2) == 1
          EOT
                    fi

      - name: Debug Check
        run: |
          cat testing.py

      - name: Install Pytest
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest

      - name: Running test file
        run: |
          source venv/bin/activate
          pytest testing.py
