name: Testing Python Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pytest
        run: |
          /opt/hostedtoolcache/Python/3.11.11/x64/bin/python -m pip install --upgrade pip
          /opt/hostedtoolcache/Python/3.11.11/x64/bin/python -m pip install pytest

      - name: Check and Add testing.py
        run: |
          if [ ! -f "testing.py" ]; then
            echo "testing.py not found. Creating it..."
            cat <<EOT > testing.py
from main import Sum, Sub, Mul, Div

def test_Sum():
    assert Sum(1, 2) == 3
    assert Sum(2, 2) == 4
    assert Sum(3, 3) == 6

def test_Sub():
    assert Sub(1, 2) == -1
    assert Sub(2, 2) == 0
    assert Sub(3, 3) == 0

def test_Mul():
    assert Mul(1, 2) == 2
    assert Mul(2, 2) == 4
    assert Mul(3, 3) == 9

def test_Div():
    assert Div(1, 2) == 0.5
    assert Div(2, 2) == 1
EOT
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add testing.py
            git commit -m "Add missing testing.py file" || echo "Commit failed, continuing anyway"
          fi
          /opt/hostedtoolcache/Python/3.11.11/x64/bin/python -m pytest testing.py -v
